### PR TITLE
[fo] Adding support of custom styles parameters for fo output

### PR DESCRIPTION
**Pull request by ath-dhm**
Adding support of custom styles parameters for fo output. Main changes :
- End of use and **deletion of style.xsl stylesheet**, previously containing numerous attribute-set to apply to the fo files
- Adding Style tree structure to \<fo-paramaters\> containing the **default parameters in ddi2fo.xml**
- Adding **style variables in ddi2fo-fixed.xsl**, which can take default value or be overloaded if specified in study parameters.xsl
- **Changing models.xsl** to modify the way fo attributes are created (previously through use-attribute-sets from style.xsl, now with call of each variable created in ddi2fo-fixed)

### CODE REVIEW

**Comment by BulotF** [comment]
Far too much code. Not generic enough.

In ddi2fo-fixed, create a node variable called $style.
In a parent node, insert elements using <xsl:for-each select="$properties//fo-parameters/style/*">
Copy the element. If the element is present in the parameters, copy each of its child element as an attribute ; otherwise the same from the properties.

In the models file, just : xsl:copy-of select="$Style//general-style/@*", instead of each attribute, one by one (won't work if you add a new attribute in your parameters)
With this, you won't have 1000 more lines. Probably less than 50.

+ Some attribute-set have french names (developped by someone out of Insee and not changed since) ; can you translate them ?

**Comment by ath-dhm** [comment]
Following your comments @BulotF :
- I created a variable "style-parameters" in ddi2fo-fixed
- In models, i loop (for-each) in each set of attributes and copy their content
- Internationalization of some names still related to french
- Deleting the text-align hard-coded for fo:table-row to allow overriding + default for row-headear-line text-align is now center

**Comment by BulotF** [comment]
In models, I would have written :
<xsl:copy-of select="$style-parameters/Sequence-title/@*"/>
Instead of for-each, etc.
2*50 lines less.

Ok with everything else.

**Comment by BulotF** [comment]
The star after @ was understood as markdown code in m'y comment.

**Comment by BulotF** [comment]
@ORogel : you can merge now !

**Comment by ath-dhm** [comment]
Added all parameters to xsd DDI2FOGeneration to allow parameter overloading with Eno-WS
Updated pom.xml version to fit with dev status and version in dev branch of Eno-WS

**Pull request merged**
